"""add phone numbers to users

Revision ID: 4166e9d60bac
Revises: a21156c74fe0
Create Date: 2021-12-07 11:13:46.818775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4166e9d60bac"
down_revision = "a21156c74fe0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
